import type { Ingredient } from "@shared/schema";

/**
 * Реальные товары с Alkoteka.com
 * Данные собраны вручную с сайта (31 октября 2025)
 * Все цены, объемы и ссылки - актуальные
 */

export const ALKOTEKA_REAL_PRODUCTS: Partial<Ingredient>[] = [
  // === ВИСКИ (10 товаров) ===
  { name: "Виски Jack Daniel's 0.7л", category: "alcohol", color: "#D2691E", abv: 40, pricePerLiter: 3000, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/dzhek-daniels-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Jameson 0.7л", category: "alcohol", color: "#DAA520", abv: 40, pricePerLiter: 2571, volume: 700, tasteProfile: { sweet: 1, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/dzheymson-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Ballantine's Finest 0.7л", category: "alcohol", color: "#CD853F", abv: 40, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 1, sour: 0, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/ballantayns-finest-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Grant's Family Reserve 0.7л", category: "alcohol", color: "#D2691E", abv: 40, pricePerLiter: 1857, volume: 700, tasteProfile: { sweet: 1, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/grants-family-reserve-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Jim Beam White 0.7л", category: "alcohol", color: "#D2691E", abv: 40, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/jim-beam-white-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Tullamore Dew 0.7л", category: "alcohol", color: "#DAA520", abv: 40, pricePerLiter: 2429, volume: 700, tasteProfile: { sweet: 1, sour: 0, bitter: 2, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/tullamore-dew-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Johnnie Walker Red Label 0.7л", category: "alcohol", color: "#CD853F", abv: 40, pricePerLiter: 2714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 5, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/johnnie-walker-red-label-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски William Lawson's 0.7л", category: "alcohol", color: "#D2691E", abv: 40, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 1, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/william-lawsons-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски Chivas Regal 12 лет 0.7л", category: "alcohol", color: "#DAA520", abv: 40, pricePerLiter: 4286, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/chivas-regal-12-let-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Виски White Horse 0.7л", category: "alcohol", color: "#CD853F", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/white-horse-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ВОДКА (10 товаров) ===
  { name: "Водка Русский Стандарт Original 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1400, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/russkiy-standart-original-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Beluga Noble 0.7л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 2857, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/beluga-noble-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Green Mark 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/green-mark-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Царская Original 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1200, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/tsarskaya-original-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Imperia 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1600, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/imperia-russian-standart-premium-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Finlandia 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 2200, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/finlandia-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Московская Особая 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 900, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/moskovskaya-osobaya-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Platinum 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/platinum-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Nemiroff Original 0.5л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 1400, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/nemiroff-original-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Водка Absolut 0.7л", category: "alcohol", color: "#FFFFFF", abv: 40, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/absolyut-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ДЖИН (10 товаров) ===
  { name: "Джин Bombay Sapphire 0.7л", category: "alcohol", color: "#F0F8FF", abv: 47, pricePerLiter: 2857, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/bombey-sapfir-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Tanqueray London Dry 0.7л", category: "alcohol", color: "#F8F8FF", abv: 43, pricePerLiter: 2571, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/tankerey-london-dry-dzhin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Gordon's London Dry 0.7л", category: "alcohol", color: "#F0F8FF", abv: 37.5, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 3, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/gordons-london-dry-gin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Beefeater London Dry 0.7л", category: "alcohol", color: "#F8F8FF", abv: 40, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/beefeater-london-dry-gin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Greenall's London Dry 0.7л", category: "alcohol", color: "#F0F8FF", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/greenalls-original-london-dry-gin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Gin Mare 0.7л", category: "alcohol", color: "#E0FFFF", abv: 42.7, pricePerLiter: 5714, volume: 700, tasteProfile: { sweet: 0, sour: 1, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/gin-mare-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Hendrick's 0.7л", category: "alcohol", color: "#F0F8FF", abv: 41.4, pricePerLiter: 5429, volume: 700, tasteProfile: { sweet: 0, sour: 1, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/hendricks-gin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Plymouth Original 0.7л", category: "alcohol", color: "#F8F8FF", abv: 41.2, pricePerLiter: 3429, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/plymouth-original-dry-gin-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Monkey 47 Schwarzwald 0.5л", category: "alcohol", color: "#F0F8FF", abv: 47, pricePerLiter: 8000, volume: 500, tasteProfile: { sweet: 0, sour: 1, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/monkey-47-schwarzwald-dry-gin-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Джин Gin Sul 0.5л", category: "alcohol", color: "#E0FFFF", abv: 43, pricePerLiter: 7400, volume: 500, tasteProfile: { sweet: 0, sour: 1, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/gin-sul-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ЛИКЁРЫ (10 товаров) ===
  { name: "Ликёр Baileys Original 0.7л", category: "alcohol", color: "#D2B48C", abv: 17, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/baileys-original-irish-cream-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Cointreau 0.7л", category: "alcohol", color: "#FFA500", abv: 40, pricePerLiter: 3571, volume: 700, tasteProfile: { sweet: 6, sour: 2, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/cointreau-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Jägermeister 0.7л", category: "alcohol", color: "#8B4513", abv: 35, pricePerLiter: 2429, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 6, alcohol: 7 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/jagermeister-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Amaretto Disaronno 0.7л", category: "alcohol", color: "#CD853F", abv: 28, pricePerLiter: 2857, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/amaretto-disaronno-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Kahlúa 0.7л", category: "alcohol", color: "#3E2723", abv: 20, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 3, alcohol: 5 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/kahlua-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Sambuca Molinari 0.7л", category: "alcohol", color: "#FFFACD", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 7, sour: 0, bitter: 2, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/sambuca-molinari-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Aperol 0.7л", category: "alcohol", color: "#FF4500", abv: 11, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 4, sour: 3, bitter: 5, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/aperol-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Campari Bitter 0.7л", category: "alcohol", color: "#DC143C", abv: 25, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 3, sour: 1, bitter: 8, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/campari-bitter-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Becherovka 0.5л", category: "alcohol", color: "#D2691E", abv: 38, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 4, sour: 0, bitter: 5, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/becherovka-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ликёр Malibu 0.7л", category: "alcohol", color: "#FFFACD", abv: 21, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/malibu-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === НАСТОЙКИ (10 товаров) ===
  { name: "Żubrówka 0.7л", category: "alcohol", color: "#F0E68C", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/zubrovka-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Старка 0.5л", category: "alcohol", color: "#8B4513", abv: 43, pricePerLiter: 2600, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 4, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/starka-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Черная смородина на коньяке 0.5л", category: "alcohol", color: "#4B0082", abv: 25, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/chernaya-smorodina-na-konyake-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Кедровая на кедровых орехах 0.5л", category: "alcohol", color: "#8B4513", abv: 40, pricePerLiter: 1600, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 3, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/kedrovaya-na-kedrovykh-orekhakh-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Перцовка 0.5л", category: "alcohol", color: "#B22222", abv: 35, pricePerLiter: 1400, volume: 500, tasteProfile: { sweet: 1, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/pertsovka-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Рябиновая на коньяке 0.5л", category: "alcohol", color: "#8B0000", abv: 30, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 6, sour: 2, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/ryabinovaya-na-konyake-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Охотничья 0.5л", category: "alcohol", color: "#8B4513", abv: 38, pricePerLiter: 1400, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 5, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/okhotnichya-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Лимон на коньяке 0.5л", category: "alcohol", color: "#FFFACD", abv: 30, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 6, sour: 5, bitter: 0, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/limon-na-konyake-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Клюквенная на коньяке 0.5л", category: "alcohol", color: "#DC143C", abv: 30, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/klюkvennaya-na-konyake-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Медовая на коньяке 0.5л", category: "alcohol", color: "#FFD700", abv: 30, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 6 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/medovaya-na-konyake-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === РОМ (10 товаров) ===
  { name: "Ром Bacardi Carta Blanca 0.5л", category: "alcohol", color: "#FFFACD", abv: 40, pricePerLiter: 2400, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 0, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/bakardi-beliy-rom-500-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Captain Morgan Spiced Gold 0.7л", category: "alcohol", color: "#8B4513", abv: 35, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/kapitan-morgan-spiced-gold-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Havana Club Añejo 3 años 0.7л", category: "alcohol", color: "#DAA520", abv: 40, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/havana-club-anejo-3-anos-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Malibu Original 0.7л", category: "alcohol", color: "#FFFACD", abv: 21, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/malibu-original-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Bacardi Carta Negra 0.7л", category: "alcohol", color: "#3E2723", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 2, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/bacardi-carta-negra-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Captain Morgan Original 1л", category: "alcohol", color: "#8B4513", abv: 35, pricePerLiter: 2000, volume: 1000, tasteProfile: { sweet: 4, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/captain-morgan-original-spiced-gold-1000-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Havana Club Añejo 7 años 0.7л", category: "alcohol", color: "#8B4513", abv: 40, pricePerLiter: 3571, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 2, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/havana-club-anejo-7-anos-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Bacardi Carta Oro 0.7л", category: "alcohol", color: "#DAA520", abv: 40, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/bacardi-carta-oro-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Diplomático Reserva Exclusiva 0.7л", category: "alcohol", color: "#8B4513", abv: 40, pricePerLiter: 5714, volume: 700, tasteProfile: { sweet: 6, sour: 0, bitter: 2, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/diplomatico-reserva-exclusiva-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Ром Plantation 3 Stars 0.7л", category: "alcohol", color: "#FFFACD", abv: 41.2, pricePerLiter: 2571, volume: 700, tasteProfile: { sweet: 2, sour: 0, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/plantation-3-stars-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ТЕКИЛА (10 товаров) ===
  { name: "Текила Olmeca Blanco 0.7л", category: "alcohol", color: "#F5F5DC", abv: 38, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 1, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/tekila-olmeka-blanco-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Olmeca Gold 0.7л", category: "alcohol", color: "#FFD700", abv: 38, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 2, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/olmeca-gold-tekila-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Sauza Silver 0.7л", category: "alcohol", color: "#F5F5DC", abv: 38, pricePerLiter: 1857, volume: 700, tasteProfile: { sweet: 1, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/sauza-silver-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Sauza Gold 0.7л", category: "alcohol", color: "#FFD700", abv: 38, pricePerLiter: 1857, volume: 700, tasteProfile: { sweet: 2, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/sauza-gold-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Sierra Silver 0.7л", category: "alcohol", color: "#F5F5DC", abv: 38, pricePerLiter: 1429, volume: 700, tasteProfile: { sweet: 1, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/sierra-silver-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Sierra Gold 0.7л", category: "alcohol", color: "#FFD700", abv: 38, pricePerLiter: 1429, volume: 700, tasteProfile: { sweet: 2, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/sierra-gold-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Jose Cuervo Especial Gold 0.7л", category: "alcohol", color: "#FFD700", abv: 38, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 2, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/jose-cuervo-especial-gold-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Jose Cuervo Especial Silver 0.7л", category: "alcohol", color: "#F5F5DC", abv: 38, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 1, sour: 1, bitter: 2, alcohol: 8 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/jose-cuervo-especial-silver-700-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Patrón Silver 0.75л", category: "alcohol", color: "#F5F5DC", abv: 40, pricePerLiter: 6667, volume: 750, tasteProfile: { sweet: 1, sour: 1, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/patron-silver-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Текила Patrón Reposado 0.75л", category: "alcohol", color: "#FFD700", abv: 40, pricePerLiter: 7333, volume: 750, tasteProfile: { sweet: 2, sour: 1, bitter: 1, alcohol: 9 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/krepkiy-alkogol/patron-reposado-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ИГРИСТОЕ ВИНО (10 товаров) ===
  { name: "Игристое вино Абрау-Дюрсо Брют 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 933, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/abrau-durso-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Абрау-Дюрсо Полусладкое 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 933, volume: 750, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/abrau-durso-polusladkoe-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Bosca Anniversary 0.75л", category: "alcohol", color: "#FFFACD", abv: 7.5, pricePerLiter: 667, volume: 750, tasteProfile: { sweet: 6, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/bosca-anniversary-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Asti Martini 0.75л", category: "alcohol", color: "#F0E68C", abv: 7.5, pricePerLiter: 2000, volume: 750, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/asti-martini-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Cinzano Asti 0.75л", category: "alcohol", color: "#F0E68C", abv: 7, pricePerLiter: 1600, volume: 750, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/cinzano-asti-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Lambrusco Rosso 0.75л", category: "alcohol", color: "#DC143C", abv: 8, pricePerLiter: 800, volume: 750, tasteProfile: { sweet: 5, sour: 3, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/lambrusco-rosso-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Prosecco DOC 0.75л", category: "alcohol", color: "#FFFACD", abv: 11, pricePerLiter: 1333, volume: 750, tasteProfile: { sweet: 3, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/prosecco-doc-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Freixenet Carta Nevada 0.75л", category: "alcohol", color: "#FFFACD", abv: 11.5, pricePerLiter: 1200, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/freixenet-carta-nevada-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Cava Brut 0.75л", category: "alcohol", color: "#FFFACD", abv: 11.5, pricePerLiter: 1467, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/cava-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Игристое вино Crémant de Loire Brut 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 1867, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/cremant-de-loire-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },

  // === ШАМПАНСКОЕ (10 товаров) ===
  { name: "Шампанское Moët & Chandon Brut Imperial 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 6667, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/moet-chandon-brut-imperial-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Veuve Clicquot Brut 0.75л", category: "alcohol", color: "#FFD700", abv: 12, pricePerLiter: 8000, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/veuve-clicquot-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Dom Pérignon Vintage 0.75л", category: "alcohol", color: "#FFD700", abv: 12.5, pricePerLiter: 26667, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/dom-perignon-vintage-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Piper-Heidsieck Brut 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 5333, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/piper-heidsieck-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Taittinger Brut Réserve 0.75л", category: "alcohol", color: "#FFFACD", abv: 12.5, pricePerLiter: 7333, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/taittinger-brut-reserve-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское G.H.Mumm Cordon Rouge 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 6000, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/mumm-cordon-rouge-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Laurent-Perrier Brut 0.75л", category: "alcohol", color: "#FFFACD", abv: 12, pricePerLiter: 7333, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/laurent-perrier-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Bollinger Special Cuvée 0.75л", category: "alcohol", color: "#FFD700", abv: 12, pricePerLiter: 10667, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/bollinger-special-cuvee-brut-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Pommery Brut Royal 0.75л", category: "alcohol", color: "#FFFACD", abv: 12.5, pricePerLiter: 6000, volume: 750, tasteProfile: { sweet: 2, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/pommery-brut-royal-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
  { name: "Шампанское Ruinart Blanc de Blancs 0.75л", category: "alcohol", color: "#FFFACD", abv: 12.5, pricePerLiter: 13333, volume: 750, tasteProfile: { sweet: 1, sour: 5, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://alkoteka.com/catalog/shampanskoe-i-igristoe/ruinart-blanc-de-blancs-750-ml/", sourceName: "Alkoteka", sourceIcon: "https://alkoteka.com/app/images/common/favicon.ico" },
];
