import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_TEQUILA: Partial<Ingredient>[] = [
  { name: "Текила Ольмека Золотая", category: "alcohol", subtype: "Текила", color: "#FFD700", abv: 38, pricePerLiter: 1857, volume: 700, tasteProfile: { sweet: 4, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/_0_7_13/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной текила Ольмека Белая", category: "alcohol", subtype: "Текила", color: "#F0F0F0", abv: 38, pricePerLiter: 1857, volume: 700, tasteProfile: { sweet: 3, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/__177/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Текила Эсполон Бланко", category: "alcohol", subtype: "Текила", color: "#F0F0F0", abv: 40, pricePerLiter: 2133, volume: 750, tasteProfile: { sweet: 3, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/__311/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Текила Эсполон Репосадо", category: "alcohol", subtype: "Текила", color: "#FFD700", abv: 40, pricePerLiter: 2133, volume: 750, tasteProfile: { sweet: 4, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/__312/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коктейль Альта Коста Сильвер с текилой", category: "alcohol", subtype: "Текила", color: "#F0F0F0", abv: 38, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 5, sour: 3, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/kokteyl_alta_kosta_silver_s_tekiloy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Текила Эсполон Аньехо", category: "alcohol", subtype: "Текила", color: "#D2691E", abv: 40, pricePerLiter: 2667, volume: 750, tasteProfile: { sweet: 5, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/tekila_espolon_anekho/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Дон Чику Текила Серебро", category: "alcohol", subtype: "Текила", color: "#F0F0F0", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/napitok_spirtnoy_don_chiku_tekila_serebro/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Текила Сиерра Бланко", category: "alcohol", subtype: "Текила", color: "#F0F0F0", abv: 38, pricePerLiter: 1600, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/tekila/napitok_spirtnoy_tekila_sierra_blanko_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
