import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_WHISKEY_PART2: Partial<Ingredient>[] = [
  // === Страница 2 ===
  { name: "Виски Фокс энд Догс 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_3__62/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Теннесси Джек Дениелс", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 4286, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_2__2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Наки Томпсон 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 800, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_naki_tompson/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Грейс 4 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1143, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_4_40/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Макаллан Дабл Каск 12 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 8571, volume: 700, tasteProfile: { sweet: 6, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_12_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Дюарс Белая Этикетка 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_dewar_s_white_label_40_0_7_12_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Тичерс Хайланд Крим 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_40_0_7_7/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Дюарс Португиз Смуз 8 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_dyuars_portugiz_smuz_kupazhir_8_let_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Чивас Ригал 12 лет 0.5л", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 3600, volume: 500, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_12_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Вильям Лоусонс 3 года 0.7л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1286, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_vilyam_lousons_ne_menee_3_let_kupazhirovannyy_napitok_pepsi_kola_2sht/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Зе Гуардиан", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 900, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_kupazhirovannyy_shotlandskiy_ze_guardian/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Фоулерс Персик с виски", category: "alcohol", subtype: "Виски", color: "#FFDAB9", abv: 35, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 7, sour: 2, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nastoyka_foulers_persik_na_osnove_viski_p_sl/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Таверн Хаунд Яблоко на основе виски", category: "alcohol", subtype: "Виски", color: "#90EE90", abv: 35, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nastoyka_p_sl_tavern_khaund_yabloko_na_osnove_viski_burbon_stayl/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Маклеод", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_makleod/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски купажированный Инаизуми", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 2857, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_inaizumi_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Рэдворкер", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_redvorker/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Гранжстоун бурбон каск финиш", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 2857, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_granzhstoun_burbon_kask_finish_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Олд Смагглер", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1286, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_old_smaggler/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джеймс Барли зерновой 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_zernovoy_dzheyms_barli/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Нобл Стаг Спайсд", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 35, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/napitok_spirtnoy_zernovoy_distillirovannyy_kupazhirovannyy_nobl_stag_spaysd__1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Сир Эдвардс шотландский", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1143, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_sir_edvarts_shotlandskiy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джим Бим Эппл", category: "alcohol", subtype: "Виски", color: "#90EE90", abv: 32.5, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 6, sour: 3, bitter: 2, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_dzhim_bim_eppl_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Джим Бим Блэк Черри", category: "alcohol", subtype: "Виски", color: "#8B0000", abv: 32.5, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 6, sour: 2, bitter: 2, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/napitok_spirtnoy_dzhim_bim_blek_cherri/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
