import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_VERMOUTH: Partial<Ingredient>[] = [
  { name: "Напиток виноградосодержащий Мартини Бьянко белый сладкий 0.5л", category: "alcohol", subtype: "Вермут", color: "#FFFACD", abv: 15, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/napitok_aromatizirovannyy_vinogradosoderzhashchiy_martini_byanko_belyy_sladkiy_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток виноградосодержащий Мартини Фиеро сладкий 0.5л", category: "alcohol", subtype: "Вермут", color: "#FF6347", abv: 14.9, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/napitok_aromatizirovannyy_vinogradosoderzhashchiy_martini_fiero_sladkiy_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток виноградосодержащий Мартини Фиеро сладкий 0.75л", category: "alcohol", subtype: "Вермут", color: "#FF6347", abv: 14.9, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/napitok_aromatizirovannyy_vinogradosoderzhashchiy_martini_fiero_sladkiy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток виноградосодержащий Мартини Бьянко белый сладкий 0.75л", category: "alcohol", subtype: "Вермут", color: "#FFFACD", abv: 15, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/napitok_aromatizirovannyy_vinogradosoderzhashchiy_martini_byanko_belyy_sladkiy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Набор Мартини Фиеро + 2 банки тоника", category: "alcohol", subtype: "Вермут", color: "#FF6347", abv: 14.9, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/nabor_iz_1_but_arom_nap_martini_fiero_i_2ban_s_pelleg_0_33l_p_u_italiya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Набор Мартини Бьянко + 2 банки тоника", category: "alcohol", subtype: "Вермут", color: "#FFFACD", abv: 15, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/nabor_martini_byanko_2_banki_tonika/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток виноградосодержащий Мартини Экстра Драй белый сухой", category: "alcohol", subtype: "Вермут", color: "#FFFACD", abv: 18, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 1, sour: 2, bitter: 4, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/napitok_aromatizirovannyy_vinogradosoderzhashchiy_martini_ekstra_dray_belyy_sukhoy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Плодовый напиток ароматизированный Вермут Чеаро квонти Бьянко", category: "alcohol", subtype: "Вермут", color: "#FFFACD", abv: 18.5, pricePerLiter: 400, volume: 1000, tasteProfile: { sweet: 6, sour: 1, bitter: 3, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vermut/plodovyy_alkogolnyy_napitok_aromatizirovannyy_vermut_chearo_kvonti_byanko/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
