import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_SPARKLING_WINE: Partial<Ingredient>[] = [
  { name: "Вино игристое Атто Примо Асти белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7.5, pricePerLiter: 800, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_atto_primo_asti_docg_zashch_naim_bel_sl_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сидр Чеароквонти Бьянко фруктовый газированный", category: "alcohol", subtype: "Вино игристое", color: "#F5DEB3", abv: 6, pricePerLiter: 400, volume: 750, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/sidr_chearokvonti_byanko_fruktovyy_gazirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Мартини Брют белое брют", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 11.5, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_martini_bryut_bel_bryut/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Мондоро Асти DOCG белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7.5, pricePerLiter: 1200, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/_docg_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Мартини Асти DOCG белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7.5, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__988/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Исси Мальвазия Спуманте белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7, pricePerLiter: 667, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__475/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Корте дей Рови Просекко Экстра Драй белое сухое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 11, pricePerLiter: 867, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/_doc__13/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Шато Тамань розовое брют", category: "alcohol", subtype: "Вино игристое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 667, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__1232/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Коллекция Винодела белое брют", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 12.5, pricePerLiter: 533, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_pino_blan_kollektsiya_vinodela_bel_bryut/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Чинзано Асти DOCG белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7, pricePerLiter: 1067, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/_docg__1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Сант Орсола Асти ДОКГ белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7, pricePerLiter: 933, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_sant_orsola_asti_docg_bel_sl/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Куатро Валли Ламбруско Бьянко Эмилия белое сладкое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 7.5, pricePerLiter: 600, volume: 750, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_kuatro_valli_lambrusko_byanko_emiliya_beloe_sladkoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Мондоро Просекко DOC белое сухое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 11, pricePerLiter: 1467, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__2199/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Атто Примо Просекко Драй белое сухое", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 11.5, pricePerLiter: 800, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/vino_igristoe_atto_primo_prosekko_doc_beloe_sukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Корте дей Рови Пино Гриджо Спуманте Экстра Драй белое брют", category: "alcohol", subtype: "Вино игристое", color: "#FFFACD", abv: 11, pricePerLiter: 867, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__1602/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино игристое Корте дей Рови Пино Гриджо Розе Спуманте Экстра Драй розовое брют", category: "alcohol", subtype: "Вино игристое", color: "#FFB6C1", abv: 11, pricePerLiter: 867, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 0, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino_igristoe_shampanskoe/vino_igristoe/__1738/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
