import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_TINCTURES_PART2: Partial<Ingredient>[] = [
  // === Страница 2 ===
  { name: "Настойка Русская мозаика клюква на коньяке сладкая", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 18.5, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_russkaya_mozaika_klyukva_na_konyake/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Царская крепость рябина на коньяке", category: "alcohol", subtype: "Настойка", color: "#FF6347", abv: 21, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 2, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_tsarskaya_krepost_ryabina_na_konyake/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Царская оригинальная смородина", category: "alcohol", subtype: "Настойка", color: "#4B0082", abv: 38, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 3, sour: 4, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_tsarskaya_originalnaya_smorodina/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Смородинка сладкая 24%", category: "alcohol", subtype: "Настойка", color: "#4B0082", abv: 24, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 8, sour: 4, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_smorodinka_sladkaya_24_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Царская оригинальная клюквенная", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 38, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 3, sour: 5, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_tsarskaya_originalnaya_klyukvennaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Горыныч Мед и Перец горькая", category: "alcohol", subtype: "Настойка", color: "#FFD700", abv: 36.6, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 5, sour: 0, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorynych_med_i_perets_gorkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Горыныч Хреновуха горькая", category: "alcohol", subtype: "Настойка", color: "#F0E68C", abv: 36.6, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 1, sour: 0, bitter: 8, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorynych_khrenovukha_gorkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Смородинка сладкая 0.1л", category: "alcohol", subtype: "Настойка", color: "#4B0082", abv: 24, pricePerLiter: 500, volume: 100, tasteProfile: { sweet: 8, sour: 4, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_smorodinka_sladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Полугар №1 рожь и пшеница", category: "alcohol", subtype: "Настойка", color: "#F5DEB3", abv: 38.5, pricePerLiter: 1400, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/napitok_spirtnoy_polugar_1_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Байкал Клюква полусладкая", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 38, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 5, sour: 5, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_baykal_klyukva_polusladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Байкал на кедровых орешках горькая", category: "alcohol", subtype: "Настойка", color: "#8B4513", abv: 38, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_baykal_na_kedrovykh_oreshkakh_gorkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Белая березка Алтайская облепиха полусладкая", category: "alcohol", subtype: "Настойка", color: "#FFA500", abv: 35, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 6, sour: 4, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_belaya_berezka_altayskaya_oblepikha_polusladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Белая березка Карельская малина полусладкая", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 35, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 6, sour: 3, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_belaya_berezka_karelskaya_malina_polusladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Царская груша", category: "alcohol", subtype: "Настойка", color: "#9ACD32", abv: 38, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 4, sour: 2, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_tsarskaya_grusha/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Сиббиттер Брусника полусладкая", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 20, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 6, sour: 4, bitter: 2, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sibbitter_brusnika_polusladkaya_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Сиббиттер Земляника полусладкая", category: "alcohol", subtype: "Настойка", color: "#FF1493", abv: 20, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sibbitter_zemlyanika_sladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Сиббиттер Кедровые Орехи горькая", category: "alcohol", subtype: "Настойка", color: "#8B4513", abv: 35, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 5, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sibbitter_kedrovye_orekhi_gorkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Сиббиттер Морошка сладкая", category: "alcohol", subtype: "Настойка", color: "#FFB347", abv: 18.5, pricePerLiter: 450, volume: 500, tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sibbitter_moroshka_sladkaya_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
