import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_LIQUEURS: Partial<Ingredient>[] = [
  // === Страница 1 ===
  { name: "Напиток спиртной Апероль 0.7л", category: "alcohol", subtype: "Ликёр", color: "#FF6600", abv: 11, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 6, sour: 4, bitter: 5, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/napitok_spirtnoy_aperol_aperitiv/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер М-р Вайлдмейстер 0.2л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 1000, volume: 200, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_desertnyy_m_r_vayldmeyster/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Мариба Рио сливки с ароматом ванили", category: "alcohol", subtype: "Ликёр", color: "#F5DEB3", abv: 15, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/29834-liker_emulsionnyy_mariba_rio_slivki_s_aromatom_vanili_15_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Ягермайстер 0.7л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 5, sour: 1, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/25522-liker-yagermayster-35-0-7/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Апероль 0.375л", category: "alcohol", subtype: "Ликёр", color: "#FF6600", abv: 11, pricePerLiter: 1867, volume: 375, tasteProfile: { sweet: 6, sour: 4, bitter: 5, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/napitok_spirtnoy_aperol_aperitiv_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Мариба Рио сливки с ароматом шоколада", category: "alcohol", subtype: "Ликёр", color: "#8B4513", abv: 15, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 2, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/29683-liker_emulsionnyy_mariba_rio15_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер М-р Вайлдмейстер 0.5л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/36012-liker_desertnyy_vayldmeyster_m_r_35_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Ягермайстер 0.04л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 2500, volume: 40, tasteProfile: { sweet: 5, sour: 1, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_desertnyy_yagermayster/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Ягермайстер 0.2л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 2000, volume: 200, tasteProfile: { sweet: 5, sour: 1, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/__116/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Амаретто Браво", category: "alcohol", subtype: "Ликёр", color: "#8B4513", abv: 20, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/27160-liker_desertnyy_amaretto_bravo_20_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Бэйлис сливочный оригинальный", category: "alcohol", subtype: "Ликёр", color: "#F5DEB3", abv: 17, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/__541/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Дон Амаретто Милано 0.1л", category: "alcohol", subtype: "Ликёр", color: "#8B4513", abv: 20, pricePerLiter: 500, volume: 100, tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/27626-liker_desertnyy_don_amaretto_milano_20_0_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Лимончелло Сан Ламаджо", category: "alcohol", subtype: "Ликёр", color: "#FFFF00", abv: 25, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 7, sour: 6, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_limonchello_san_lamadzho/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Ягодамастер Ботаникал 0.5л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 6, sour: 2, bitter: 4, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_desertnyy_yagodamaster_botanikal/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Барон Руссак Трипл Сек", category: "alcohol", subtype: "Ликёр", color: "#FFA500", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_krepkiy_baron_russak_tripl_sek/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Ягодамастер Ботаникал 0.25л", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 35, pricePerLiter: 800, volume: 250, tasteProfile: { sweet: 6, sour: 2, bitter: 4, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_yagodamaster_botanikal/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коктейль Рафине Шоколад и Вишня", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 30, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 9, sour: 1, bitter: 2, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/kokteyl_rafine_shokolad_i_vishnya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коктейль Рафине Шоколад и Ваниль", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 30, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/kokteyl_rafine_shokolad_i_vanil/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Барон Руссак Кокос", category: "alcohol", subtype: "Ликёр", color: "#FFFFFF", abv: 21, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_baron_roussac_coconut_caribbean_rum/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Барон Руссак Ирландские Сливки", category: "alcohol", subtype: "Ликёр", color: "#F5DEB3", abv: 19, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_baron_roussac_irish_cream_slivochnyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },

  // === Страница 2 ===
  { name: "Коктейль Рафине шоколад и инжир", category: "alcohol", subtype: "Ликёр", color: "#654321", abv: 30, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/kokteyl_rafine_shokolad_i_inzhir/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Кампари (аперитив)", category: "alcohol", subtype: "Ликёр", color: "#DC143C", abv: 25, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 4, sour: 2, bitter: 8, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_desertnyy_kampari_aperitiv/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Найт Габриелло Лимончелло", category: "alcohol", subtype: "Ликёр", color: "#FFFF00", abv: 25, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 7, sour: 6, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_nayt_gabriello_limonchello/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ликер Старейшина Альпин Хани", category: "alcohol", subtype: "Ликёр", color: "#FFD700", abv: 34, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/likery/liker_stareyshina_alpin_khani/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
