import type { Ingredient } from "@shared/schema";

// Розовое вино с сайта Красное&Белое
// Фильтр по розовому вину (объем 0.37-1л, крепость 8-15%)
export const KRASNOEIBELOE_WINE_ROSE: Partial<Ingredient>[] = [
  { name: "Вино Бриза ду Мар Винью Верде розовое полусухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 10, pricePerLiter: 733, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_briza_du_mar_vinyu_verde_rozovoe_polusukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Галеоне Примитиво Салеттино розовое сухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 1133, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_galeone_primitivo_salentino_rozovoe_sukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Маре Альта Винью Верде розовое полусухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 10, pricePerLiter: 960, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_mare_alta_vinyu_verde_rozovoe_polusukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Бродлиф Совиньон Блан розовое полусухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 867, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_brodlif_sovinon_blan_rozovoe_polusukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Катуна Шираз розовое полусухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 733, volume: 750, tasteProfile: { sweet: 2, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_katuna_shiraz_rozovoe_polusukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино П.В.С.& Б Стеларис Розе розовое сухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 733, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_p_v_s_b_stelaris_roze_rozovoe_sukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Рио Рика Розе Ла Манча розовое полусладкое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 10.5, pricePerLiter: 533, volume: 750, tasteProfile: { sweet: 5, sour: 3, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_rio_rika_roze_la_mancha_rozovoe_polusladkoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Сан оф Африка Кейп Роуз розовое полусладкое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 12.5, pricePerLiter: 600, volume: 750, tasteProfile: { sweet: 5, sour: 3, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_san_of_afrika_keyp_rouz_rozovoe_polusladkoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Вино Сол де Плата Мальбек Розе розовое сухое", category: "alcohol", subtype: "Вино розовое", color: "#FFB6C1", abv: 13, pricePerLiter: 787, volume: 750, tasteProfile: { sweet: 1, sour: 4, bitter: 1, alcohol: 3 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vino/vino_sol_de_plata_malbek_roze_rozovoe_sukhoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
