import type { Ingredient } from "@shared/schema";

/**
 * Газированные напитки с krasnoeibeloe.ru (Часть 2 из 2)
 * Данные собраны вручную (1 ноября 2025)
 */

export const KRASNOEIBELOE_SODAS_PART2: Partial<Ingredient>[] = [
  // === СТРАНИЦА 2 ===
  { name: "Фруктовая Fresh Bar Jelly Bears 0.48л", category: "soda", color: "#FF6347", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_fresh_bar_jelly_bears/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Рич индиан тоник 1л", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 3, sour: 4, bitter: 2, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gaz_voda_rich_indiana_tonik_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Крафт Роял Клубника и Киви 0.41л ст", category: "soda", color: "#FF1493", abv: 0, pricePerLiter: 145, volume: 410, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_kraft_royal_klubnika_i_kivi_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Апельсиновая Экспорт Стаил 2л", category: "soda", color: "#FFA500", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_export_style_apelsin/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимон-Лайм Экспорт Стаил 2л", category: "soda", color: "#32CD32", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 4, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_export_style_limon_laym/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Крафт Роял Фейхоа и ягоды Асаи 0.41л ст", category: "soda", color: "#9370DB", abv: 0, pricePerLiter: 145, volume: 410, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_kraft_royal_feykhoa_i_yagody_asai_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Эвервесс Биттер Лемон 1л", category: "soda", color: "#FFFFE0", abv: 0, pricePerLiter: 80, volume: 1000, tasteProfile: { sweet: 4, sour: 5, bitter: 2, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_evervess_bitter_lemon/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Fresh Bar Мерри Берри 0.48л", category: "soda", color: "#DC143C", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_fresh_bar_merry_berry/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Рич биттер лимон 1л", category: "soda", color: "#FFFFE0", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 4, sour: 5, bitter: 2, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gaz_voda_rich_biter_limon/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Добрый без сахара 1л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 75, volume: 1000, tasteProfile: { sweet: 3, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_bezalkogolnyy_silnogazirovannyy_dobryy_kola_bez_sakhara/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Fresh Bar Ванилла 0.48л", category: "soda", color: "#8B4513", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 7, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_fresh_bar_kola_vanilla/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Старые Добрые Традиции 0.5л ст", category: "soda", color: "#FFFACD", abv: 0, pricePerLiter: 120, volume: 500, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_starye_dobrye_traditsii_limonad_steklo/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Лаймон Фреш 0.33л ж/б", category: "soda", color: "#32CD32", abv: 0, pricePerLiter: 150, volume: 330, tasteProfile: { sweet: 5, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_laymon_fresh_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Гринми Стресс Контрол 0.33л ж/б", category: "soda", color: "#8B008B", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_grinmi_stress_kontrol_yagody_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Гринми Иммунити Протект 0.33л ж/б", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 5, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_grinmi_immuniti_protekt_tsitrus_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Лаймон фреш макс 1л", category: "soda", color: "#32CD32", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 5, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_laymon_fresh_maks_1l/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Fresh Bar Лимон 0.48л", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_fresh_bar_kola_limon/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Fresh Bar Мелонейд Мохито 0.48л", category: "soda", color: "#98FB98", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_fresh_bar_meloneyd_mokhito/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },

  // === СТРАНИЦА 3 ===
  { name: "Фруктовая Ессентуки Тархун 0.5л ст", category: "soda", color: "#90EE90", abv: 0, pricePerLiter: 120, volume: 500, tasteProfile: { sweet: 5, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_essentuki_tarkhun_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Зиззи D витамин 0.33л ж/б", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_zizzi_d_vitamin_bezalkogolnyy_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Зиззи В витамин 0.33л ж/б", category: "soda", color: "#FF6347", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_zizzi_v_vitamin_bezalkogolnyy_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Зиззи С витамин 0.33л ж/б", category: "soda", color: "#FFA500", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 5, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_zizzi_s_vitamin_bezalkogolnyy_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Милк Вэйв Сладкая вата 0.5л", category: "soda", color: "#FFB6C1", abv: 0, pricePerLiter: 120, volume: 500, tasteProfile: { sweet: 8, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_milk_veyv_s_so_vkusom_sladkaya_vata/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Милк Вэйв клубника 0.33л ж/б", category: "soda", color: "#FF69B4", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_milk_veyv_s_klubnika_bezalkogolnyy_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Милк Вэйв манго маракуйя 0.33л ж/б", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_milk_veyv_s_mango_marakuyya_bezalkogolnyy_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Натахтари Груша 1.5л", category: "soda", color: "#F0E68C", abv: 0, pricePerLiter: 80, volume: 1500, tasteProfile: { sweet: 6, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_natakhtari_grusha_bezalkogolnyy_srednegazirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Натахтари Груша 0.5л ст", category: "soda", color: "#F0E68C", abv: 0, pricePerLiter: 140, volume: 500, tasteProfile: { sweet: 6, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_natakhtari_grusha_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Натахтари Саперави 1.5л", category: "soda", color: "#8B0000", abv: 0, pricePerLiter: 80, volume: 1500, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_natakhtari_saperavi_bezalkogolnyy_srednegazirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Натахтари Саперави 0.5л ст", category: "soda", color: "#8B0000", abv: 0, pricePerLiter: 140, volume: 500, tasteProfile: { sweet: 5, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_natakhtari_saperavi_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Натахтари Фейхоа 0.5л ст", category: "soda", color: "#90EE90", abv: 0, pricePerLiter: 140, volume: 500, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_natakhtari_feykhoa_st_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад Рич Биттер Лемон 1.5л", category: "soda", color: "#FFFFE0", abv: 0, pricePerLiter: 67, volume: 1500, tasteProfile: { sweet: 4, sour: 5, bitter: 2, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_rich_bitter_lemon/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Рич Коктейль Спритц 0.33л ж/б", category: "soda", color: "#FF6347", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 6, sour: 4, bitter: 1, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_rich_kokteyl_spritts_krasnyy_apelsin_zh_b_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Эвервесс 0.25л ст", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 200, volume: 250, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_evervess_kola_bezalkogolnyy_silnogazirovannyy_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
