import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_WHISKEY_PART3: Partial<Ingredient>[] = [
  // === Страница 3 ===
  { name: "Напиток спиртной Нобл Стаг Яблоко", category: "alcohol", subtype: "Виски", color: "#90EE90", abv: 35, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/napitok_spirtnoy_nobl_stag_yabloko/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Фоулерс Вишня на основе виски", category: "alcohol", subtype: "Виски", color: "#8B0000", abv: 35, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 7, sour: 2, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nastoyka_foulers_vishnya_na_osnove_viski_polusladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Аберфелди 12 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 7143, volume: 700, tasteProfile: { sweet: 6, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_aberfeldi_12let_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Глен Морей Сингл Молт Оур Классик", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 3429, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_glen_morey_singl_molt_our_klassik/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Хайланд Парк 12 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 5714, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_khaylend_park_12_let_viking_khonor_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Сир Эдвардс шотландский 0.2л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1200, volume: 200, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_sir_edvards_shotlandskiy_kupazhirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Мэйкерс Марк", category: "alcohol", subtype: "Бурбон", color: "#8B4513", abv: 45, pricePerLiter: 3429, volume: 700, tasteProfile: { sweet: 6, sour: 0, bitter: 3, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_meykers_mark/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Тилинг Смол Бэтч", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 46, pricePerLiter: 4286, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 4, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_tiling_smol_betch/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Скотс Грэй шотландский", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1143, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_skots_grey_shotlandskiy_kupazhirovannyy_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Блэк Рэм 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1143, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_blek_rem_3_goda_kupazhirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Вильям Лоусонс 3 года 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1200, volume: 250, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_vilyam_lousons_kupazhirovannyy_ne_menee_3_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Дюарс Френч Смуз 8 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_dyuars_french_smuz_kupazhirovannyy_8_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Клиган 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_kligan_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Клиган 0.1л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 100, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_kligan/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Сончо купажированный", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 857, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_soncho_kupazhirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Фоулерс зерновой 0.1л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 700, volume: 100, tasteProfile: { sweet: 3, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_foulers_zernovoy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Фэймос Грауз 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1800, volume: 500, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_kupazhirovannyy_feymos_grauz/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Набор Виски Вильям Лоусонс + 2 банки Rich Кола", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1286, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nabor_viski_vilyam_lousons_2_banki_rich_kola/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток висковый Золотой Джокер ж/б", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/napitok_viskovyy_zolotoy_dzhoker_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Вильям Лоусонс Супер Спайсд 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 35, pricePerLiter: 900, volume: 250, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/napitok_spirtnoy_vilyam_lousons_super_spaysd/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Фоулерс персик с виски 0.25л", category: "alcohol", subtype: "Виски", color: "#FFDAB9", abv: 35, pricePerLiter: 720, volume: 250, tasteProfile: { sweet: 7, sour: 2, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nastoyka_foulers_persik_s_viski_polusladkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
