import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_COCKTAILS: Partial<Ingredient>[] = [
  { name: "Напиток пивной Мистер Крафт Манго Маракуйя Ананас", category: "soda", subtype: "Коктейли", color: "#FFA500", abv: 6, pricePerLiter: 143, volume: 420, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/pivnoy_napitok_mister_kraft_paster_so_vkusom_mango_marakuyi_i_ananasa_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Регстаерс джин тоник лимон лайм", category: "soda", subtype: "Коктейли", color: "#FFFF99", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 5, sour: 5, bitter: 2, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/__2049/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Пик Ап черная смородина", category: "soda", subtype: "Коктейли", color: "#663399", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_pik_ap_chernaya_smorodina/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Регстаерс джин тоник грейпфрут", category: "soda", subtype: "Коктейли", color: "#FFB6C1", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 4, sour: 6, bitter: 3, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_regstaers_dzhin_tonik_greypfrut_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Регстаерс джин тоник манго маракуйя", category: "soda", subtype: "Коктейли", color: "#FFA500", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_regstaers_dzhin_tonik_mango_marakuyya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Фримен Джин тоник", category: "soda", subtype: "Коктейли", color: "#FFFF99", abv: 7, pricePerLiter: 120, volume: 500, tasteProfile: { sweet: 5, sour: 4, bitter: 2, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_frimen_dzhin_tonik_pet/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Фримен Джин тоник грейпфрут", category: "soda", subtype: "Коктейли", color: "#FFB6C1", abv: 7, pricePerLiter: 120, volume: 500, tasteProfile: { sweet: 4, sour: 6, bitter: 3, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_frimen_dzhin_tonik_greypfrut_pet_7_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Пик Ап клубника и земляника", category: "soda", subtype: "Коктейли", color: "#FF1493", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_pik_ap_klubnika_i_zemlyanika_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Аморе Пина Колада", category: "soda", subtype: "Коктейли", color: "#FFFACD", abv: 6, pricePerLiter: 133, volume: 450, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_amore_pina_kolada/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Аморе сладкая клубника", category: "soda", subtype: "Коктейли", color: "#FF1493", abv: 6, pricePerLiter: 133, volume: 450, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_amore_sladkaya_klubnika_zh_b_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Доктор Дизель вишня персик", category: "soda", subtype: "Коктейли", color: "#FF6347", abv: 5, pricePerLiter: 125, volume: 400, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 1 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_doktor_dizel_vishnya_persik_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Доктор Дизель малина лайм", category: "soda", subtype: "Коктейли", color: "#DC143C", abv: 5, pricePerLiter: 125, volume: 400, tasteProfile: { sweet: 6, sour: 5, bitter: 0, alcohol: 1 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_doktor_dizel_malina_laym_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Мистер Крафт черная малина лайм", category: "soda", subtype: "Коктейли", color: "#8B008B", abv: 6, pricePerLiter: 143, volume: 420, tasteProfile: { sweet: 6, sour: 5, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_mister_kraft_chernaya_malina_laym_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Немирофф Голубые Гавайи", category: "soda", subtype: "Коктейли", color: "#00BFFF", abv: 7, pricePerLiter: 182, volume: 330, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_nemiroff_golubye_gavayi_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Немирофф черника гранат черная смородина ром", category: "soda", subtype: "Коктейли", color: "#663399", abv: 7, pricePerLiter: 182, volume: 330, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_nemiroff_chernika_granat_chernaya_smorodina_rom_st_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Пик Ап арбузный мохито", category: "soda", subtype: "Коктейли", color: "#90EE90", abv: 5, pricePerLiter: 152, volume: 330, tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 1 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_pik_ap_arbuznyy_mokhito_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Пик Ап виски и кола", category: "soda", subtype: "Коктейли", color: "#654321", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_pik_ap_viski_i_kola_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Пик Ап коньяк и миндаль", category: "soda", subtype: "Коктейли", color: "#D2691E", abv: 7, pricePerLiter: 140, volume: 430, tasteProfile: { sweet: 7, sour: 0, bitter: 1, alcohol: 2 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/energetiki_kokteyli/__7/napitok_pivnoy_pik_ap_konyak_i_mindal_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
