import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_JUICES_PART1: Partial<Ingredient>[] = [
  { name: "Нектар мультифрукт 1.93л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 41, volume: 1930, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_multifruktovyy_divnyy_sad_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Крал Гранатовый 1л", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 150, volume: 1000, tasteProfile: { sweet: 6, sour: 5, bitter: 1, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/__445/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Добрый Мультифрукт 2л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 55, volume: 2000, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/24646-nektar-dobryy-multifrukt-2-0-6/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Рич Грейпфрут 1л", category: "juice", color: "#FFB6C1", abv: 0, pricePerLiter: 90, volume: 1000, tasteProfile: { sweet: 4, sour: 6, bitter: 3, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/22220-sok-rich-greypfrut-1l-/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Рич Вишня 1л", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 85, volume: 1000, tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/21901-nektar-rich-vishnya-1l-/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток Добрый Палпи Апельсин", category: "juice", color: "#FFA500", abv: 0, pricePerLiter: 78, volume: 900, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/sokosoderzhashchie-napitki/21851-napitok-dobryy-apelsin-s-myakotyu-0-9/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Рич Яблоко 1л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 85, volume: 1000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/22223-sok-rich-yabloko-1l-/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Рич Томат с солью 1л", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 85, volume: 1000, tasteProfile: { sweet: 3, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/22222-sok-rich-tomat-1l-/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Рич Ананас с мякотью 1л", category: "juice", color: "#FFD700", abv: 0, pricePerLiter: 90, volume: 1000, tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/__395/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Крал манго 1л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 140, volume: 1000, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_kral_mango/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Крал Гранатовый 0.25л", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 280, volume: 250, tasteProfile: { sweet: 6, sour: 5, bitter: 1, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_granatovyy_pryamogo_otzhima/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток Морсэль клюква 1л", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 5, sour: 6, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/sokosoderzhashchie-napitki/napitok_b_a_negaz_morsel_klyukva_i_brusnika/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок ФрутоНяня Яблоко 0.2л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/__1767/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья яблочный 1л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/__2087/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар яблочный 1.93л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 41, volume: 1930, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_yablochnyy_divnyy_sad_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья томат", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 74, volume: 950, tasteProfile: { sweet: 3, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_tomatnyy_s_solyu_s_myakotyu/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья томат 1л", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 3, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_sady_pridonya_sok_tomatnyy_s_solyu_s_myakotyu_vosstanovlennyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Морс DeVita клюквенный 1л", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 75, volume: 1000, tasteProfile: { sweet: 5, sour: 6, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/sokosoderzhashchie-napitki/mors_devita_klyukvennyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Мой мультифрукт 0.2л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/detskiy_nektar_moy_multifrukt/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья 0.95л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 74, volume: 950, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_multifrutovyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья яблоко", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 74, volume: 950, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_yablochnyy_osvetl/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья яблоко-смор", category: "juice", color: "#8B008B", abv: 0, pricePerLiter: 75, volume: 1000, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/__1526/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Крал вишня 1л", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 140, volume: 1000, tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_kral_vishnya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
