import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_WHISKEY_PART1: Partial<Ingredient>[] = [
  // === Страница 1 ===
  { name: "Виски Фоулерс 0.7л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_zernovoy_foulers/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Нобл Стаг 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_nobl_stag_3_goda_kupazhirovannyy_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джонни Уокер Рэд Лейбл", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/__536/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски бурбон Джим Бим 4 года 1л", category: "alcohol", subtype: "Бурбон", color: "#8B4513", abv: 40, pricePerLiter: 1500, volume: 1000, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/__477/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джеймс Барли 0.1л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 500, volume: 100, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_dzheyms_barli/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Вильям Лоусонс Супер Спайсд 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 35, pricePerLiter: 857, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/spirtnoy_nap_vilyam_lousons_super_spaysd_vyderzhka_3_goda/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Висковый напиток крепкий Золотой Джокер", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/37217-napitok_viskovyy_krepkiy_zolotoy_dzhoker_40_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джемесон", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_jameson_40_0_7_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски зерновой Маккаллистер 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_zernovoy_makkalister/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Наки Томпсон Эппл Пай на основе виски", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 35, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 7, sour: 2, bitter: 2, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/nastoyka_polusladkaya_naki_tompson_eppl_pay_na_osnove_viski_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Фоулерс 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 714, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_foulers/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Наки Томпсон 3 года 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_naki_tompson_3_goda_kupazhirovannyy_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Наки Томпсон 3 года 0.7л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 857, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_naki_tompson_3_goda_kupazhirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Нобл Стаг 0.7л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_nobl_stag_3_goda_kupazhirovannyy_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Чивас Ригал 12 лет", category: "alcohol", subtype: "Виски", color: "#8B4513", abv: 40, pricePerLiter: 3429, volume: 700, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/34097-viski_chivas_rigal_kupazh_12_let_v_p_k_40_0_7/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Баллантайнс Файнест 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_3__59/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Лаки Наки", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_kupazhirovannyy_laki_naki_vyderzhka_3_goda_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Вильям Лоусонс 3 года 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_3__43/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Фэймос Грауз 3 года", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/_3__50/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Маккаллистер 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_makkallister/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Вильям Лоусонс Супер Спайсд 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 35, pricePerLiter: 900, volume: 500, tasteProfile: { sweet: 4, sour: 0, bitter: 3, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/__1353/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски бурбон Джим Бим 0.75л", category: "alcohol", subtype: "Бурбон", color: "#8B4513", abv: 40, pricePerLiter: 1467, volume: 750, tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_burbon_dzhim_bim/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Нобл Стаг 0.5л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_nobl_stag_3_goda_kupazhirovannyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Виски Джеймс Барли 0.25л", category: "alcohol", subtype: "Виски", color: "#D2691E", abv: 40, pricePerLiter: 500, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/viski/viski_dzheyms_barli_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
