import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_TINCTURES_PART1: Partial<Ingredient>[] = [
  // === Страница 1 ===
  { name: "Настойка горькая Немирофф Украинская Медовая с перцем 0.5л", category: "alcohol", subtype: "Настойка", color: "#FFD700", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 6, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_nemiroff_medovaya_s_pertsem/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Золотой Джокер 0.5л", category: "alcohol", subtype: "Настойка", color: "#DAA520", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/37104-nastoyka_gorkaya_zolotoy_dzhoker_40_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Лимонка сладкая 0.5л", category: "alcohol", subtype: "Настойка", color: "#FFFF00", abv: 29, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 8, sour: 5, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_limonka_sladkaya_so_vkusom_limona_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Немирофф Украинская Медовая с перцем 0.25л", category: "alcohol", subtype: "Настойка", color: "#FFD700", abv: 40, pricePerLiter: 800, volume: 250, tasteProfile: { sweet: 6, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_nemiroff_medovaya_s_pertsem_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Пермская Люкс 0.25л", category: "alcohol", subtype: "Настойка", color: "#8B4513", abv: 35, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 2, sour: 0, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_permskaya_lyuks_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Немирофф клюква на коньяке 0.25л", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 21, pricePerLiter: 700, volume: 250, tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_klyukva_na_konyake_nemiroff_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Золотой Джокер 0.25л", category: "alcohol", subtype: "Настойка", color: "#DAA520", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 3, sour: 0, bitter: 5, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/37876-nastoyka_gorkaya_zolotoy_dzhoker_40_0_25/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Лимонка сладкая 0.1л", category: "alcohol", subtype: "Настойка", color: "#FFFF00", abv: 29, pricePerLiter: 500, volume: 100, tasteProfile: { sweet: 8, sour: 5, bitter: 0, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_limonka_sladkaya_so_vkusom_limona/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Абсент Фримен горькая", category: "alcohol", subtype: "Настойка", color: "#9ACD32", abv: 60, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 8, alcohol: 9 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/__1964/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Марьяж коньячная клюква", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 23, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/36413-nastoyka_sladkaya_maryazh_konyachnaya_s_aromatom_klyukvy_23_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Честная перцовая", category: "alcohol", subtype: "Настойка", color: "#FF4500", abv: 40, pricePerLiter: 800, volume: 375, tasteProfile: { sweet: 1, sour: 0, bitter: 7, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/21889-nast-gorkaya-chestnaya-pertsovaya-40-0-375-/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Немирофф Вишня в шоколаде", category: "alcohol", subtype: "Настойка", color: "#8B0000", abv: 21, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 9, sour: 2, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_nemiroff_vishnya_v_shokolade/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Марьяж коньячная рябина", category: "alcohol", subtype: "Настойка", color: "#FF6347", abv: 23, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 7, sour: 3, bitter: 2, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/36414-nastoyka_sladkaya_maryazh_konyachnaya_s_aromatom_ryabiny_23_0_5_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Медовая Услада", category: "alcohol", subtype: "Настойка", color: "#FFD700", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 7, sour: 0, bitter: 3, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_medovaya_uslada/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Немирофф Клюква крепкая", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 38, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 3, sour: 5, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastroyka_gorkaya_nemiroff_klyukva_krepkaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка сладкая Немирофф клюква на коньяке 0.5л", category: "alcohol", subtype: "Настойка", color: "#DC143C", abv: 21, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_klyukva_na_konyake_nemiroff_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка горькая Пермская Люкс 0.5л", category: "alcohol", subtype: "Настойка", color: "#8B4513", abv: 35, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 6, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_gorkaya_permskaya_lyuks/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Самогон Немирофф на кедровых орехах", category: "alcohol", subtype: "Настойка", color: "#8B4513", abv: 38, pricePerLiter: 900, volume: 500, tasteProfile: { sweet: 3, sour: 0, bitter: 4, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/samogon_nemiroff_na_kedrovykh_orekhakh/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Настойка Немирофф сладкая черная смородина", category: "alcohol", subtype: "Настойка", color: "#4B0082", abv: 21, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 8, sour: 4, bitter: 0, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/nastoyka/nastoyka_sladkaya_nemiroff_chernaya_smorodina/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
