import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_BEER: Partial<Ingredient>[] = [
  // === Импортное пиво ===
  { name: "Пиво Белорусское светлое 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.2, pricePerLiter: 100, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_belorusskoe_svetloe_filtrovannoe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Штайнингер Пилс 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.8, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_shtayninger_pils_svetloe_filtrovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Штайнингер Хефевайсбир 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFE4B5", abv: 5.2, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 4, sour: 2, bitter: 4, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_shtayninger_khefevaysbir_svetloe_nefiltrovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Эрзманн Лайт 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 2, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_erzmann_light_svetloe_st_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Фельдшлёсхен Пилснер 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.9, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_feldshleckhen_cvetl_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Фельдшлёсхен Пэйл Вит 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFE4B5", abv: 5, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 4, sour: 2, bitter: 4, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_feldshlyeskhen_peyl_vit_svetloe_pshenichnoe_nefiltr_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Мерфис Айриш Стаут 0.5л", category: "alcohol", subtype: "Пиво", color: "#3D2817", abv: 4, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 3, sour: 1, bitter: 7, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_merfiz_ayrish_staut_temnoe_filtrovannoe_pasterizovannoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Хофбройхаус Фрайзинг Урхелл 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.9, pricePerLiter: 180, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_khofbroykhaus_frayzing_urkhell_svetloe_filtrovannoe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Кромбахер Пилс 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.8, pricePerLiter: 200, volume: 500, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_krombakher_pils_svetloe_filtrovannoe_zh_b_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Эрзман Лайт 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 2, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_erzman_layt_sv_paster_filtrovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Корона Экстра 0.355л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.5, pricePerLiter: 338, volume: 355, tasteProfile: { sweet: 2, sour: 3, bitter: 4, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/napitok_pivnoy_korona_ekstra_svetloe_pasterizovannoe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Арарат светлое 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.5, pricePerLiter: 140, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_ararat_svetloe_filtrovannoe_st_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Будвайзер Будвар 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 200, volume: 500, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_budvayzer_budvar_svetloe_filtrovannoe_pasterizovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Гиннесс Драфт 0.44л", category: "alcohol", subtype: "Пиво", color: "#3D2817", abv: 4.2, pricePerLiter: 273, volume: 440, tasteProfile: { sweet: 3, sour: 1, bitter: 7, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_ginness_draft_temnoe_filtrovannoe_pasterizovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Гюмри Голд 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.5, pricePerLiter: 140, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/importnoe_pivo/pivo_gyumri_gold_svetloe_filtrovannoe_st_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },

  // === Российское пиво ===
  { name: "Пиво Жатецкий Гусь 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.6, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1944/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Эфес Пилсенер 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1345/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Жигули 1968 0.43л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.5, pricePerLiter: 116, volume: 430, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_zhiguli_1968_svetloe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Белый Медведь 1.15л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 70, volume: 1150, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_belyy_medved_svetloe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Балтика №9 Крепкое 1.2л", category: "alcohol", subtype: "Пиво", color: "#DAA520", abv: 8, pricePerLiter: 83, volume: 1200, tasteProfile: { sweet: 3, sour: 1, bitter: 6, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_baltika_9_krepkoe_legendarnoe_svetloe_pet/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Охота Крепкое 0.43л", category: "alcohol", subtype: "Пиво", color: "#DAA520", abv: 8.1, pricePerLiter: 116, volume: 430, tasteProfile: { sweet: 3, sour: 1, bitter: 6, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_okhota_krepkoe_svetloe_zh_b_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Балтика №3 Классическое 0.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.8, pricePerLiter: 100, volume: 500, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_baltika_3_svetloe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Балтика №9 Крепкое 0.45л", category: "alcohol", subtype: "Пиво", color: "#DAA520", abv: 8, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 1, bitter: 6, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_baltika_9_krepkoe_svetloe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Немецкое светлое 1.5л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4, pricePerLiter: 53, volume: 1500, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_nemetskoe_svetloe_pasterizovannoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Гринбит 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.6, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_grinbit_svetloe_pasterizovannoe_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Ловенбрау 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5.4, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1331/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Т9 светлое 0.45л", category: "alcohol", subtype: "Пиво", color: "#DAA520", abv: 8, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 1, bitter: 6, alcohol: 8 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/_9__1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Бад светлое 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1329/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Гринбит светлое 0.45л ст", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.6, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_grinbit_svetloe_pasterizovannoe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Велкопоповицкий Козел 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1518/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Бад светлое 0.44л ст", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 114, volume: 440, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_bad_svetloe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Стелла Артуа 0.44л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 136, volume: 440, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_stella_artua_svetloe_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Балтика №3 0.45л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.8, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/_3__42/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Москвич 0.43л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 4.3, pricePerLiter: 116, volume: 430, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_moskvich_svetloe_pasterizovannoe_zh_b_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Эфес Пилсенер 0.45л жб", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 2, sour: 2, bitter: 6, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1485/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток пивной Велкопоповицкий Козел темное 0.45л", category: "alcohol", subtype: "Пиво", color: "#8B4513", abv: 3.7, pricePerLiter: 111, volume: 450, tasteProfile: { sweet: 4, sour: 1, bitter: 5, alcohol: 4 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/__1339/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Пиво Жигулевское Бочковое 1.15л", category: "alcohol", subtype: "Пиво", color: "#FFD700", abv: 5, pricePerLiter: 70, volume: 1150, tasteProfile: { sweet: 3, sour: 2, bitter: 5, alcohol: 5 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rossiyskoe/pivo_zhigulevskoe_bochkovoe_svetloe_pasterizovannoe/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
