import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_VODKA: Partial<Ingredient>[] = [
  { name: "Водка Русский Стандарт", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 857, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/_40_0_7_10/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Медведь 0.5л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__499/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Ханская", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__876/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Медведь 1л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 500, volume: 1000, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__501/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка особая Немирофф пшеница 1л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 700, volume: 1000, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_osobaya_nemiroff_pshenitsa_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Тундра Аутентик", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_tundra_autentik/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Старлей", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 550, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__503/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Калашников Премиум", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_kalashnikov_premium/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Царский кубок", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_tsarskiy_kubok/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Царская 0.7л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_tsarskaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка особая Немирофф Пшеница 0.5л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_nemiroff_pshenitsa/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Царская Оригинальная 0.25л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 700, volume: 250, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_tsarskaya_originalnaya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Избушка 0.25л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 500, volume: 250, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_izbushka/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Славянская мягкая на березовых почках", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 1, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/_40_0_5_22/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Белуга Нобл", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 2000, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__1160/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Нектар Колоска на Молоке", category: "alcohol", subtype: "Водка", color: "#FFFACD", abv: 40, pricePerLiter: 650, volume: 500, tasteProfile: { sweet: 2, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/23003-vodka-nektar-koloska-na-moloke-40-0-5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Пять Озер 0.25л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 600, volume: 250, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_pyat_ozer_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Пять Озер 0.375л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 600, volume: 375, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_pyat_ozer_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка особая Зеленая Марка Кедровая 0.1л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 700, volume: 100, tasteProfile: { sweet: 1, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/30568-vodka_osobaya_zelenaya_marka_kedrovaya_40_0_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Талка 0.5л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 550, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/21453-vodka-talka-40-0-5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Талка 0.25л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 550, volume: 250, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__121/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Хаски Арктический лёд", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_khaski_arkticheskiy_lyed/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Избушка 0.5л", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 0, sour: 0, bitter: 1, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/vodka_izbushka_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Водка Сталковская Альфа", category: "alcohol", subtype: "Водка", color: "#F0F0F0", abv: 40, pricePerLiter: 800, volume: 375, tasteProfile: { sweet: 0, sour: 0, bitter: 0, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/vodka_nastoyki/vodka/__1195/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
