import type { Ingredient } from "@shared/schema";

/**
 * Газированные напитки с krasnoeibeloe.ru (Часть 1 из 2)
 * Данные собраны вручную (1 ноября 2025)
 * Всего товаров: 57
 * Цены примерные (50-80₽/л для больших объемов, 120-180₽/л для малых)
 */

export const KRASNOEIBELOE_SODAS_PART1: Partial<Ingredient>[] = [
  // === СТРАНИЦА 1 ===
  { name: "Кола Добрый 0.3л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 150, volume: 300, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gaz_voda_dobryy_kola_pet/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Экспорт Стаил 0.5л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 100, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_eksport_stail_klassik_kola_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Экспорт Стаил 2л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_eksport_stail_klassik_kola/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Fresh Bar 0.48л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovnnyy_napitok_fresh_bar_kola/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Апельсиновая Добрый 1л", category: "soda", color: "#FFA500", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_apelsin/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Экспорт Стаил 0.33л ж/б", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 150, volume: 330, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_eksport_stail_kola_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Апельсиновая Добрый 2л", category: "soda", color: "#FFA500", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_apelsin_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Fresh Bar Cola Banana 0.48л", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 7, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_fresh_bar_cola_banana/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Добрый 0.33л ст", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 150, volume: 330, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_dobryy_kola_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Экспорт Стаил 1л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 60, volume: 1000, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_eksport_stail_klassik_kola_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Любимая 2л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 40, volume: 2000, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_lyubimaya_kola_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Добрый 0.33л ж/б", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 150, volume: 330, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_kola_zh_b/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Добрый 1л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_kola_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимон-Лайм Добрый 2л", category: "soda", color: "#32CD32", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 4, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_limon_laym/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Цитрус Fresh Bar 0.48л", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 125, volume: 480, tasteProfile: { sweet: 5, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_fresh_bar_tsitrus_ays/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Fresh Bar 1.5л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 60, volume: 1500, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/gazirovannyy_napitok_fresh_bar_kola/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимон-Лайм Добрый 1л", category: "soda", color: "#32CD32", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 4, sour: 5, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_limon_laym_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Милкис клубника 0.25л ж/б", category: "soda", color: "#FF69B4", abv: 0, pricePerLiter: 200, volume: 250, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/21499-molochno-klubnichnyy-napitok-milkis-gaz-0-25/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Милкис 0.25л ж/б", category: "soda", color: "#E6E6FA", abv: 0, pricePerLiter: 200, volume: 250, tasteProfile: { sweet: 6, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/21498-molochnyy-napitok-milkis-gaz-0-25/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Джуси Берри Тропик 0.75л", category: "soda", color: "#FF6347", abv: 0, pricePerLiter: 80, volume: 750, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dzhusi_berri_tropik/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Лимонад 1.5л", category: "soda", color: "#FFFACD", abv: 0, pricePerLiter: 60, volume: 1500, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/silnogaz_napitok_b_a_limonad/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Фримен Джин Арбуз и Лайм 0.33л ст", category: "soda", color: "#90EE90", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 6, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_bezalkogolnyy_frimen_dzhin_arbuz_i_laym_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Фруктовая Фримен Ром Ананас и Кокос 0.33л ст", category: "soda", color: "#FFD700", abv: 0, pricePerLiter: 180, volume: 330, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_bezalkogolnyy_frimen_rom_ananas_i_kokos_st/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Кола Добрый 2л", category: "soda", color: "#00BFFF", abv: 0, pricePerLiter: 45, volume: 2000, tasteProfile: { sweet: 6, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/gazirovannaya-voda/napitok_b_a_silnogaz_dobryy_kola/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
