import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_JUICES_PART2: Partial<Ingredient>[] = [
  { name: "Сок Мой зеленое яблоко 0.2л", category: "juice", color: "#90EE90", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_moy_zelenoe_yabloko/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья черешня", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 79, volume: 950, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_chereshnya_aroniya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток Добрый Апельсин 2л", category: "juice", color: "#FFA500", abv: 0, pricePerLiter: 55, volume: 2000, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/napitok_sokosoderzhashchiy_dobryy_apelsin_mandarin/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico", imageUrl: "https://krasnoeibeloe.servicecdn.ru/upload/resize_cache/iblock/f5f/een22d3en21bxrii0xefa5vfv2dm2los/200_356_1/mandarin_040624_t.jpg" },
  { name: "Нектар Добрый Яблоко 2л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 55, volume: 2000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_dobryy_yabloko_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Добрый Томат 2л", category: "juice", color: "#DC143C", abv: 0, pricePerLiter: 55, volume: 2000, tasteProfile: { sweet: 3, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_dobryy_tomat/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток Алоэ Вера 0.525л", category: "juice", color: "#90EE90", abv: 0, pricePerLiter: 143, volume: 525, tasteProfile: { sweet: 5, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/sokosoderzhashchie-napitki/napitok_aloe_vera_dzhus_b_a/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок ФрутоНяня яблоко-вишня", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_frutonyanya_yabloko_vishnya_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар DeVita яблоко-вишня 1л", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_devita_yabloko_vishnya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья 1.93л", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 46, volume: 1930, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_multifruktovyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар DeVita яблочный 1л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 70, volume: 1000, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_yablochnyy_devita_1l/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Ми ми мишки мультифрукт", category: "juice", color: "#FF8C00", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_mi_mi_mishki_multifrukt/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток Organic арбуз-алоэ", category: "juice", color: "#FFB6C1", abv: 0, pricePerLiter: 143, volume: 525, tasteProfile: { sweet: 6, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/sokosoderzhashchie-napitki/napitok_organic_arbuz_aloe_negazirovannyy_bezalkogolnyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Ми ми мишки банан 0.2л", category: "juice", color: "#FFD700", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 8, sour: 1, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_mi_mi_mishki_banan/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Рич Апельсин 1л", category: "juice", color: "#FFA500", abv: 0, pricePerLiter: 85, volume: 1000, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/nektar_rich_apelsin/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Нектар Сады Придонья яблочный", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 46, volume: 1930, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/nektary/nektar_sady_pridonya_yablochnyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Агуша яблоко 0.2л", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_agusha_yablochnyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Агуша яблоко-персик", category: "juice", color: "#FFDAB9", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_agusha_yabloko_persik_s_myakotyu/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Ми ми мишки яблоко-вишня", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_mi_mi_mishki_yablochno_vishnyevyy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья зеленое яб", category: "juice", color: "#90EE90", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_sady_pridonya_zelenoe_yabloko/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья яблоко-вишня", category: "juice", color: "#8B0000", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 7, sour: 3, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_sady_pridonya_yabloko_vishnya/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Сок Сады Придонья яблоко-груша", category: "juice", color: "#F0E68C", abv: 0, pricePerLiter: 150, volume: 200, tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/soki-i-nektary/soki/sok_sady_pridonya_yabloko_grusha_s_myakotyu/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
