import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_RUM: Partial<Ingredient>[] = [
  { name: "Ром Мама Джама Блэк выдержанный", category: "alcohol", subtype: "Ром", color: "#654321", abv: 38, pricePerLiter: 857, volume: 700, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_mama_dzhama_blek_vyderzhannyy_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Закапа Юбилейный 23 года", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 7143, volume: 700, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/_23_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром выдержанный Сангсом", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 1429, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_vyderzhannyy_sangsom_v_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Закапа XO", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 8571, volume: 700, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/__1824/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Капитан Жан Лафитт дарк", category: "alcohol", subtype: "Ром", color: "#654321", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_kapitan_zhan_lafitt_dark/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Бругал Аньехо Супериор", category: "alcohol", subtype: "Ром", color: "#D2691E", abv: 38, pricePerLiter: 2286, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_brugal_anekho_superior/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Контрабандо 5 лет", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_kontrabando_5_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Ботран №8 Ризерва Классика", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 2143, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_botran_8_rizerva_klassika_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Матусалем Солера 7 лет", category: "alcohol", subtype: "Ром", color: "#8B4513", abv: 40, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_matusalem_solera_7_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Ром Сэнди Рэй", category: "alcohol", subtype: "Ром", color: "#D2691E", abv: 38, pricePerLiter: 714, volume: 700, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/rom_jin_tequila_liquor/rom/rom_sendi_rey/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
