import type { Ingredient } from "@shared/schema";

export const KRASNOEIBELOE_COGNAC_PART1: Partial<Ingredient>[] = [
  // === Страница 1 ===
  { name: "Коньяк Кизляр 3 года 0.25л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 400, volume: 250, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kizlyar_3_goda/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Лезгинка 5 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 500, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_lezginka_pyatiletniy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Фанагория 5 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_fanagoriya_5_let_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Киновский 4 года 0.25л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 460, volume: 250, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kinovskiy_4_goda_2/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Лезгинка 5 лет 0.25л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 500, volume: 250, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_lezginka_5_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский 5 звезд 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_5_zvezd/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Кочари 5 лет 0.25л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 800, volume: 250, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/_5__10/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Бренди Делор Фрер X.O. 0.7л", category: "alcohol", subtype: "Бренди", color: "#8B4513", abv: 40, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/brendi/brendi_delor_frer_xo_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский 5 звезд 0.25л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 700, volume: 250, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/armyanskiy_konyak_5_zvezd_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Бренди Делор Фрер В.С. 0.5л", category: "alcohol", subtype: "Бренди", color: "#D2691E", abv: 40, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/brendi/brendi_delor_frer_vs/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Киновский 4 года 0.5л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 460, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kinovskiy_4_goda/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Кочари 5 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/__158/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский 5 звезд 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 700, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_5_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Кизляр 3 года 0.5л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 400, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kizlyar_trekhletniy/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Хеннесси ВС 0.5л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 4000, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/_vs_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский 5 звезд 0.25л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 700, volume: 250, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_5_zvezd_5_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Киновский 4 года 0.1л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 460, volume: 100, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kinovskiy_4_goda_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский 5 звезд 0.1л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 700, volume: 100, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_5_zvezd_5_let_1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Бренди Торрес 10 лет Гран Резерва 0.5л", category: "alcohol", subtype: "Бренди", color: "#8B4513", abv: 38, pricePerLiter: 1600, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/brendi/32953-brendi_torres_10_let_gran_rezerva_38_0_5/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк А.де Фуссиньи ХО 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 2400, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/__692/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский Кочари 7 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 1200, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/_7__1/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Хеннесси XO 0.7л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 14286, volume: 700, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/_xo_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Старейшина Дали 10 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_stareyshina_dali_10_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },

  // === Страница 2 (часть) ===
  { name: "Бренди Делор Фрер V.S.O.P 0.7л", category: "alcohol", subtype: "Бренди", color: "#8B4513", abv: 40, pricePerLiter: 1714, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/brendi/brendi_delor_frer_vsop_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Армянский Арарат Наири 20 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 6000, volume: 500, tasteProfile: { sweet: 8, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/_20_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Курвуазье ХО 0.7л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 8571, volume: 700, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_kurvuaze_kho_ne_menee_10_let_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Напиток спиртной Арарат Априкот 0.5л", category: "alcohol", subtype: "Бренди", color: "#FFA500", abv: 35, pricePerLiter: 1200, volume: 500, tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 6 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/napit_spirt_na_osnove_konyaka_ararat_aprikot_p_k/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Бренди Семболь Националь ХО 0.7л", category: "alcohol", subtype: "Бренди", color: "#8B4513", abv: 40, pricePerLiter: 2000, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/brendi/brendi_sembol_natsional_kho/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Древняя Хива 7 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 800, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_drevnyaya_khiva_7_let_/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Дагестан старый КС 12 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 1000, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_dagestan_staryy_ks_12_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк СЕН КЛО XO 0.7л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 1571, volume: 700, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_saint_clos_xo_v_p_u/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Арарат Ахтамар 10 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 2000, volume: 500, tasteProfile: { sweet: 7, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_akhtamar/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк Беш Кудук 5 лет 0.5л", category: "alcohol", subtype: "Коньяк", color: "#8B4513", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 6, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_besh_kuduk_5_let/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" },
  { name: "Коньяк армянский 3 звезды 0.5л", category: "alcohol", subtype: "Коньяк", color: "#D2691E", abv: 40, pricePerLiter: 600, volume: 500, tasteProfile: { sweet: 5, sour: 1, bitter: 2, alcohol: 7 }, unit: "ml", sourceUrl: "https://krasnoeibeloe.ru/catalog/konyak_armanyak_brendi/konyak/konyak_armyanskiy_3_goda/", sourceName: "Красное&Белое", sourceIcon: "https://krasnoeibeloe.ru/favicon.ico" }
];
