import type { Ingredient } from "@shared/schema";

const URL = "https://www.wildberries.ru/catalog/0/search.aspx?page=1&sort=popular&search=%D1%81%D0%B8%D1%80%D0%BE%D0%BF%D1%8B+%D0%B4%D0%BB%D1%8F+%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D0%B5%D0%B9&fbrand=263215#c172715008";
const IMG = "/src/assets/syryp_ingridient_img.jpg";
const ICON = "https://avatars.mds.yandex.net/get-altay/15417312/2a0000019657128152a68f1e447f3ed1ea42/XXL_height";

export const WILDBERRIES_SYRUPS: Partial<Ingredient>[] = [
  {
    name: "Сироп Попкорн для кофе и десертов 1 л стекло",
    category: "syrup",
    color: "#D2691E",
    abv: 0,
    pricePerLiter: 268,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Карамель для кофе и коктейлей 1 л стекло",
    category: "syrup",
    color: "#CD853F",
    abv: 0,
    pricePerLiter: 275,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ваниль французская для кофе 1 л стекло",
    category: "syrup",
    color: "#F5DEB3",
    abv: 0,
    pricePerLiter: 282,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Шоколадное печенье для напитков 1 л стекло",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лесной орех для кофе и коктейлей 1 л стекло",
    category: "syrup",
    color: "#A0522D",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кокос для коктейлей и кофе 1 л стекло",
    category: "syrup",
    color: "#FFFACD",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Клубника для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FF6B9D",
    abv: 0,
    pricePerLiter: 278,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Малина для коктейлей и десертов 1 л стекло",
    category: "syrup",
    color: "#E30B5C",
    abv: 0,
    pricePerLiter: 280,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Вишня для коктейлей 1 л стекло",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Персик для коктейлей и кофе 1 л стекло",
    category: "syrup",
    color: "#FFDAB9",
    abv: 0,
    pricePerLiter: 277,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Манго для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFA500",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Маракуйя для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лайм для коктейлей 1 л стекло",
    category: "syrup",
    color: "#00FF00",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 7, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мята для коктейлей Мохито 1 л стекло",
    category: "syrup",
    color: "#98FF98",
    abv: 0,
    pricePerLiter: 280,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Имбирь для коктейлей 1 л стекло",
    category: "syrup",
    color: "#DAA520",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 1, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Голубая Лагуна Blue Curacao 1 л стекло",
    category: "syrup",
    color: "#0080FF",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Гренадин для коктейлей 1 л стекло",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 272,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Банан для коктейлей и кофе 1 л стекло",
    category: "syrup",
    color: "#FFE135",
    abv: 0,
    pricePerLiter: 279,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Апельсин для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 274,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лимон для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFFF00",
    abv: 0,
    pricePerLiter: 276,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 8, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ежевика для коктейлей 1 л стекло",
    category: "syrup",
    color: "#4B0082",
    abv: 0,
    pricePerLiter: 284,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Черная смородина для коктейлей 1 л стекло",
    category: "syrup",
    color: "#301934",
    abv: 0,
    pricePerLiter: 281,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Киви для коктейлей 1 л стекло",
    category: "syrup",
    color: "#8EE53F",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Арбуз для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FC6C85",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Дыня для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFE4B5",
    abv: 0,
    pricePerLiter: 280,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ананас для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 279,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Груша для коктейлей 1 л стекло",
    category: "syrup",
    color: "#D1E231",
    abv: 0,
    pricePerLiter: 277,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Зеленое яблоко для коктейлей 1 л стекло",
    category: "syrup",
    color: "#8DB600",
    abv: 0,
    pricePerLiter: 275,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 5, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Базилик для коктейлей 1 л стекло",
    category: "syrup",
    color: "#228B22",
    abv: 0,
    pricePerLiter: 289,
    volume: 1000,
    tasteProfile: { sweet: 5, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Огурец для коктейлей 1 л стекло",
    category: "syrup",
    color: "#90EE90",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 3, sour: 1, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Тирамису для кофе 1 л стекло",
    category: "syrup",
    color: "#D2B48C",
    abv: 0,
    pricePerLiter: 293,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Соленая карамель для кофе 1 л стекло",
    category: "syrup",
    color: "#C19A6B",
    abv: 0,
    pricePerLiter: 291,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Фундук для кофе 1 л стекло",
    category: "syrup",
    color: "#8B7355",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Миндаль для кофе 1 л стекло",
    category: "syrup",
    color: "#FFEBCD",
    abv: 0,
    pricePerLiter: 284,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Белый шоколад для кофе 1 л стекло",
    category: "syrup",
    color: "#FFFAF0",
    abv: 0,
    pricePerLiter: 289,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Молочный шоколад для кофе 1 л стекло",
    category: "syrup",
    color: "#D2691E",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Irish Cream Ирландский крем 1 л стекло",
    category: "syrup",
    color: "#C8B4A0",
    abv: 0,
    pricePerLiter: 294,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Корица для кофе и коктейлей 1 л стекло",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 282,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лаванда для коктейлей 1 л стекло",
    category: "syrup",
    color: "#967BB6",
    abv: 0,
    pricePerLiter: 296,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Бузина для коктейлей 1 л стекло",
    category: "syrup",
    color: "#301934",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Роза для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FF69B4",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Фиалка для коктейлей 1 л стекло",
    category: "syrup",
    color: "#8A2BE2",
    abv: 0,
    pricePerLiter: 297,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Чёрный чай для напитков 1 л стекло",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 281,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 4, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Зелёный чай Матча для напитков 1 л стекло",
    category: "syrup",
    color: "#7CB342",
    abv: 0,
    pricePerLiter: 299,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Личи для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFC0CB",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Гуава для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFC9DE",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Драконий фрукт Питайя 1 л стекло",
    category: "syrup",
    color: "#FF1493",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Тропические фрукты для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Жасмин для коктейлей 1 л стекло",
    category: "syrup",
    color: "#F8F8FF",
    abv: 0,
    pricePerLiter: 294,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Юзу для коктейлей 1 л стекло",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 310,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 7, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Красный апельсин Blood Orange 1 л стекло",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },

  // === НОВЫЕ 100 УНИКАЛЬНЫХ СИРОПОВ ===
  {
    name: "Сироп Голубой Кюрасао для коктейлей и лимонадов 1л пэт",
    category: "syrup",
    color: "#0080FF",
    abv: 0,
    pricePerLiter: 265,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Голубой Кюрасао для коктейлей и лимонадов 1л.",
    category: "syrup",
    color: "#0080FF",
    abv: 0,
    pricePerLiter: 268,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Красная смородина 1 л",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 280,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Голубика 1 л",
    category: "syrup",
    color: "#4169E1",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Брусника 1 л",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 5, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Клюква 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 284,
    volume: 1000,
    tasteProfile: { sweet: 5, sour: 7, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Облепиха 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Фейхоа 1 л",
    category: "syrup",
    color: "#90EE90",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Абрикос 1 л",
    category: "syrup",
    color: "#FFA500",
    abv: 0,
    pricePerLiter: 276,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Нектарин 1 л",
    category: "syrup",
    color: "#FF6347",
    abv: 0,
    pricePerLiter: 279,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Слива 1 л",
    category: "syrup",
    color: "#8B4789",
    abv: 0,
    pricePerLiter: 277,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Инжир 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Финик 1 л",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 294,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Гранат 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 289,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Черешня 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 282,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Грейпфрут 1 л",
    category: "syrup",
    color: "#FF69B4",
    abv: 0,
    pricePerLiter: 281,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 5, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мандарин 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 278,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Бергамот 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 296,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 4, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Помело 1 л",
    category: "syrup",
    color: "#FFA500",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ревень 1 л",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 284,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 6, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кумкват 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 299,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 5, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Папайя 1 л",
    category: "syrup",
    color: "#FFA500",
    abv: 0,
    pricePerLiter: 293,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Карамбола 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 297,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 4, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Рамбутан 1 л",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 310,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мангостин 1 л",
    category: "syrup",
    color: "#8B008B",
    abv: 0,
    pricePerLiter: 315,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Дуриан 1 л",
    category: "syrup",
    color: "#FFE4B5",
    abv: 0,
    pricePerLiter: 320,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Саподилла 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 305,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Тамаринд 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 5, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Маття латте 1 л",
    category: "syrup",
    color: "#7CB342",
    abv: 0,
    pricePerLiter: 302,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Эрл Грей 1 л",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 4, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Масала чай 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 289,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Улун молочный 1 л",
    category: "syrup",
    color: "#D2B48C",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Чай с бергамотом 1 л",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 284,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 1, bitter: 4, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мёд акации 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мёд каштановый 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 303,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кленовый 1 л",
    category: "syrup",
    color: "#D2691E",
    abv: 0,
    pricePerLiter: 310,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Агавы 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Топинамбур 1 л",
    category: "syrup",
    color: "#F5DEB3",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кокосовый крем 1 л",
    category: "syrup",
    color: "#FFFACD",
    abv: 0,
    pricePerLiter: 296,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ореховая паста 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 299,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Арахисовое масло 1 л",
    category: "syrup",
    color: "#DEB887",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кешью 1 л",
    category: "syrup",
    color: "#FFE4B5",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Макадамия 1 л",
    category: "syrup",
    color: "#F5DEB3",
    abv: 0,
    pricePerLiter: 315,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Пекан 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 305,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Фисташка 1 л",
    category: "syrup",
    color: "#93C572",
    abv: 0,
    pricePerLiter: 310,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Имбирный пряник 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Крем-брюле 1 л",
    category: "syrup",
    color: "#D2691E",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Чизкейк 1 л",
    category: "syrup",
    color: "#FFFACD",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Панакота 1 л",
    category: "syrup",
    color: "#FFF5EE",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Пралине 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 300,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Марципан 1 л",
    category: "syrup",
    color: "#FFEBCD",
    abv: 0,
    pricePerLiter: 297,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Нуга 1 л",
    category: "syrup",
    color: "#F5DEB3",
    abv: 0,
    pricePerLiter: 293,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Халва 1 л",
    category: "syrup",
    color: "#DEB887",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Рахат-лукум 1 л",
    category: "syrup",
    color: "#FFB6C1",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Зефир 1 л",
    category: "syrup",
    color: "#FFF0F5",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Маршмеллоу 1 л",
    category: "syrup",
    color: "#FFFFFF",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Сахарная вата 1 л",
    category: "syrup",
    color: "#FFB6C1",
    abv: 0,
    pricePerLiter: 280,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Баббл-гам 1 л",
    category: "syrup",
    color: "#FF69B4",
    abv: 0,
    pricePerLiter: 275,
    volume: 1000,
    tasteProfile: { sweet: 10, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Кола 1 л",
    category: "syrup",
    color: "#3B2414",
    abv: 0,
    pricePerLiter: 270,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Тархун 1 л",
    category: "syrup",
    color: "#00FF00",
    abv: 0,
    pricePerLiter: 272,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Дюшес 1 л",
    category: "syrup",
    color: "#D1E231",
    abv: 0,
    pricePerLiter: 274,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Барбарис 1 л",
    category: "syrup",
    color: "#DC143C",
    abv: 0,
    pricePerLiter: 276,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 7, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Байкал 1 л",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 273,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 3, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Крем-сода 1 л",
    category: "syrup",
    color: "#F5DEB3",
    abv: 0,
    pricePerLiter: 271,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Спрайт 1 л",
    category: "syrup",
    color: "#E0FFE0",
    abv: 0,
    pricePerLiter: 269,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Фанта 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 268,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мохито безалкогольный 1 л",
    category: "syrup",
    color: "#98FF98",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 4, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Пина Колада 1 л",
    category: "syrup",
    color: "#FFFACD",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Май Тай 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Космополитан 1 л",
    category: "syrup",
    color: "#FF1493",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 4, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Маргарита 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 6, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Дайкири 1 л",
    category: "syrup",
    color: "#FFE4B5",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 5, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Текила Санрайз 1 л",
    category: "syrup",
    color: "#FF6347",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Секс на пляже 1 л",
    category: "syrup",
    color: "#FF8C69",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лонг Айленд 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 293,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 3, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Апероль Шприц 1 л",
    category: "syrup",
    color: "#FF4500",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 2, bitter: 4, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Негрони 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 5, sour: 1, bitter: 6, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Американо 1 л",
    category: "syrup",
    color: "#8B4513",
    abv: 0,
    pricePerLiter: 294,
    volume: 1000,
    tasteProfile: { sweet: 5, sour: 1, bitter: 5, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Шоколадный брауни премиум 1 л",
    category: "syrup",
    color: "#654321",
    abv: 0,
    pricePerLiter: 298,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ягодный микс премиум 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 281,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Вишневый ликёр премиум 1 л",
    category: "syrup",
    color: "#800020",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Апельсиновый фреш премиум 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 278,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Мятный шоколад 1 л",
    category: "syrup",
    color: "#2E8B57",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 0, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Апельсин с корицей 1 л",
    category: "syrup",
    color: "#FF8C00",
    abv: 0,
    pricePerLiter: 287,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Вишня с миндалем 1 л",
    category: "syrup",
    color: "#8B0000",
    abv: 0,
    pricePerLiter: 289,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Клубника с базиликом 1 л",
    category: "syrup",
    color: "#FF6B9D",
    abv: 0,
    pricePerLiter: 291,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 2, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Малина с розой 1 л",
    category: "syrup",
    color: "#E30B5C",
    abv: 0,
    pricePerLiter: 293,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Лимон с лавандой 1 л",
    category: "syrup",
    color: "#FFFF00",
    abv: 0,
    pricePerLiter: 290,
    volume: 1000,
    tasteProfile: { sweet: 6, sour: 6, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Огурец с мятой 1 л",
    category: "syrup",
    color: "#90EE90",
    abv: 0,
    pricePerLiter: 285,
    volume: 1000,
    tasteProfile: { sweet: 3, sour: 2, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Грейпфрут с розмарином 1 л",
    category: "syrup",
    color: "#FF69B4",
    abv: 0,
    pricePerLiter: 294,
    volume: 1000,
    tasteProfile: { sweet: 5, sour: 5, bitter: 4, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Персик с тимьяном 1 л",
    category: "syrup",
    color: "#FFDAB9",
    abv: 0,
    pricePerLiter: 288,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 1, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Ананас с перцем чили 1 л",
    category: "syrup",
    color: "#FFD700",
    abv: 0,
    pricePerLiter: 292,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Манго с имбирем 1 л",
    category: "syrup",
    color: "#FFA500",
    abv: 0,
    pricePerLiter: 295,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 2, bitter: 2, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Яблоко с корицей 1 л",
    category: "syrup",
    color: "#8DB600",
    abv: 0,
    pricePerLiter: 279,
    volume: 1000,
    tasteProfile: { sweet: 8, sour: 3, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Груша с ванилью 1 л",
    category: "syrup",
    color: "#D1E231",
    abv: 0,
    pricePerLiter: 283,
    volume: 1000,
    tasteProfile: { sweet: 9, sour: 1, bitter: 0, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  },
  {
    name: "Сироп Черная смородина с мятой 1 л",
    category: "syrup",
    color: "#301934",
    abv: 0,
    pricePerLiter: 286,
    volume: 1000,
    tasteProfile: { sweet: 7, sour: 3, bitter: 1, alcohol: 0 },
    unit: "ml",
    sourceUrl: URL,
    sourceName: "Wildberries",
    sourceIcon: ICON,
    imageUrl: IMG
  }
];
